services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8080:8080"
    volumes:
      - ./todo.db:/root/todo.db
    env_file:
      - .env 